# пароль прописан явно для удобства проверки задания,
# в публичной базе использовались бы переменные окружения
---
db_user: docker
db_host: db
db_port: 5432
db_name: avito
db_password: 12345678
http_port: 9000